import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  text: {
    width: '100%',
    textAlign: 'center',
    paddingTop: '20%',
    color: '#fff',
    fontSize: 30,
    fontWeight: '700',
  },
  input: {
    width: '90%',
    marginLeft: '5%',
    backgroundColor: '#fff',
    color: '#000',
    borderRadius: 12,
    height: 65,
    marginTop: '66%',
    paddingLeft: 15,
    fontSize: 15,
  },
  repeat: {
    width: '90%',
    marginLeft: '5%',
    backgroundColor: '#fff',
    color: '#000',
    borderRadius: 12,
    height: 65,
    marginTop: '5%',
    paddingLeft: 15,
    fontSize: 15,
  },
  btn: {
    width: '90%',
    backgroundColor: '#FFCD61',
    borderRadius: 12,
    height: 65,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: '5%',
    marginTop: '25%',
  },
  btnTxt: {
    color: '#000',
    fontSize: 18,
    fontWeight: '700',
  },
  err: {
    color: 'red',
    textAlign: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    width: '70%',
    marginLeft: '5%',
    marginTop: '5%',
    fontWeight: '700',
  },
  success: {
    color: 'green',
    textAlign: 'center',
    backgroundColor: 'rgba(255,255,255,0.8)',
    width: '70%',
    marginLeft: '5%',
    marginTop: '5%',
    fontWeight: '700',
    fontSize: 18,
  },
});
