import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
  },
  image: {
    flex: 1,
    height: '100%',
  },
  text: {
    fontSize: 40,
    color: '#fff',
    textAlign: 'center',
    fontWeight: '700',
    paddingTop: '15%',
  },
  mid: {
    color: '#fff',
    fontWeight: '500',
    textAlign: 'center',
    paddingTop: '39%',
  },
  input: {
    height: 60,
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 6,
    opacity: 0.8,
    color: '#000',
    paddingLeft: 15,
    marginLeft: '5%',
    marginTop: '10%',
  },
  btn: {
    width: '90%',
    height: 60,
    backgroundColor: '#FFCD61',
    borderRadius: 6,
    marginLeft: '5%',
    marginTop: '5%',
  },
  btnText: {
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    paddingTop: '6%',
    textAlign: 'center',
    fontSize: 20,
    fontWeight: '600',
  },
  password: {
    height: 60,
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 6,
    opacity: 0.8,
    color: '#000',
    paddingLeft: 15,
    marginLeft: '5%',
    marginTop: '3%',
  },
  err: {
    // paddingLeft: '5%',
    color: 'red',
    backgroundColor: 'rgba(255,255,255,0.8)',
    width: '40%',
    marginLeft: '5%',
    marginTop: '2%',
    fontSize: 15,
    fontWeight: '700',
  },
});
