import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    width: '100%',
    height: '100%',
    position: 'relative',
    backgroundColor: 'white',
  },
  image: {
    width: '100%',
    height: '27%',
    position: 'relative',
  },
  back: {
    color: 'black',
    position: 'absolute',
    top: '3%',
    left: '5%',
    fontSize: 24,
  },
  love: {
    // left: '90%',
    // top: '200%',
    tintColor: 'black',
  },
  name: {
    fontSize: 30,
    fontWeight: '700',
    color: 'black',
    left: '5%',
    paddingTop: '2%',
  },
  price: {
    fontSize: 30,
    fontWeight: '700',
    color: 'black',
    left: '5%',
  },
  capacity: {
    fontSize: 22,
    fontWeight: '500',
    left: '5%',
  },
  prepayment: {
    fontSize: 22,
    fontWeight: '500',
    left: '5%',
  },
  avail: {
    fontSize: 22,
    fontWeight: '500',
    left: '5%',
    color: 'green',
  },
  location: {
    position: 'absolute',
    fontWeight: '600',
    left: '20%',
    top: '52.5%',
    fontSize: 20,
  },
  inputDate: {
    backgroundColor: '#efefef',
    position: 'absolute',
    top: '77%',
    left: '5%',
    width: '50%',
    opacity: 1,
    height: '7.1%',
    color: 'white',
  },
  dayInput: {
    backgroundColor: '#efefef',
    marginTop: '18%',
    width: '35%',
    height: '7.3%',
    marginLeft: '60%',
    borderRadius: 10,
  },
  btn: {
    backgroundColor: '#FFCD61',
    height: '8%',
    width: '90%',
    marginTop: '8%',
    marginLeft: '5%',
    borderRadius: 10,
  },
  btnText: {
    fontSize: 20,
    fontWeight: '700',
    textAlign: 'center',
    paddingTop: '5%',
  },
});
