import {StyleSheet} from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    height: '100%',
  },
  image: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  text: {
    paddingTop: 70,
    paddingLeft: 15,
    fontSize: 45,
    color: 'white',
  },
  email: {
    marginLeft: '10%',
    paddingLeft: 20,
    height: 60,
    width: '80%',
    color: 'black',
    marginTop: '5%',
    backgroundColor: '#FFFF',
    opacity: 0.8,
    borderRadius: 6,
  },
  password: {
    marginLeft: '10%',
    height: 60,
    width: '80%',
    color: 'black',
    backgroundColor: '#FFFF',
    marginTop: '5%',
    opacity: 0.8,
    paddingLeft: 20,
    borderRadius: 6,
    justifyContent: 'center',
  },
  name: {
    marginLeft: '10%',
    height: 60,
    width: '80%',
    color: 'black',
    backgroundColor: '#FFFF',
    marginTop: '5%',
    opacity: 0.8,
    paddingLeft: 20,
    borderRadius: 6,
    justifyContent: 'center',
  },
  forgot: {
    paddingTop: '3%',
    color: '#fff',
    textAlign: 'center',
  },
  button: {
    width: '80%',
    backgroundColor: '#FFCD61',
    height: 60,
    marginTop: '30%',
    marginLeft: '10%',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 6,
  },
  btnText: {
    fontWeight: '800',
    fontSize: 18,
    color: '#393939',
  },
  signup: {
    paddingTop: '3%',
    color: '#FFF',
    textAlign: 'center',
  },
  error: {
    color: 'red',
    fontWeight: '600',
    paddingTop: '1%',
    textAlign: 'center',
  },
});
